---
  swagger: "2.0"
  info:
    title: "Process instances Sample API"
    description: "This is a sample API for process instances."
    version: "0.0.1"
  host: "localhost:9000"
  schemes:
    - "http"
  consumes:
     - application/ld+json
  produces:
     - application/ld+json